### ISSUE TITLE
A ton of text in the log

### ISSUE THREAD

**Issue by moonfather1** [Jusey1/ItemsDisplayForge#2]
game fails to parse loot tables and prints out large stack traces for each block where i don't have its related mod. the game works, i just have tons of red text in the console.

example 1:
`Couldn't parse element loot_tables:items_displayed:blocks/hero_pottery_sherd
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'alexscaves:hero_pottery_sherd'`

example 2:
`Couldn't parse element loot_tables:items_displayed:blocks/kobold_armor_trim
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'kobolds:kobold_template'`

**Comment by Jusey1** [comment]
Ye'h, that's to be expected. Nothing to worry about really.
